### ISSUE TITLE
More Pennsylvania Coffee Roasters

### ISSUE THREAD

**Issue by zachlebar** [alexcarpenter/alexcarpenter-11ty#40]
# Black and Brass Coffee Roasters
https://blackandbrasscoffee.com
520 Main St
Honesdale, PA 18431

# Electric City Roasting Co.
http://electriccityroasting.com
1201 Marshwood Road, Suite A
Throop, PA 18411

# Backyard Beans Coffee Company
https://www.backyardbeans.com
408 West Main Street,
Lansdale, PA, 19446

**Comment by alexcarpenter** [comment]
@zachlebar Thanks! Added https://github.com/alexcarpenter/us-coffee-roasters/commit/b0514e68cbf2eb58b769dccfbb52d8a1a905ab10
