### ISSUE TITLE
Merit Roasting Co. - San Antonio, Texas

### ISSUE THREAD

**Issue by bzerangue** [alexcarpenter/alexcarpenter-11ty#41]
Merit Roasting Co.  
2001 S Presa St, San Antonio, TX 78210  
Ph. (210) 259-8201  
Web: <https://meritcoffee.com/>

**Comment by alexcarpenter** [comment]
@bzerangue Added, thanks! https://github.com/alexcarpenter/us-coffee-roasters/commit/8b68618a30cc77340a725ab55eb6574ab3f328ae
