### ISSUE TITLE
Add HTML "prefix" attribute for Open Graph "og" CURIEs.

### ISSUE THREAD

**Issue by jbenner-radham** [alexcarpenter/alexcarpenter-11ty#9]
I saw your site via your Designer News post (nice site BTW, I like really like the design) and just wanted to make a suggestion. I noticed that you don't have the "prefix" attribute defined for your Open Graph CURIEs. You can fix this by adding it in like this: `<head prefix="og: http://ogp.me/ns#">`.

**Comment by alexcarpenter** [comment]
Interesting, not to familiar with open graph tags. I make use of the [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) plugin to manage all of the SEO type stuff. Will take a look, thanks!
